'use strict';

const Collection = require('./collection.js');
const schema = {
  id: { type: 'string', required: true },
  name: { type: 'string', required: true },
  display_name: { type: 'string', required: true },
  description: { type: 'string' },
};

/**
 * @typedef Categories
 * @property {string} id.required - unique ID generated by uuid upon creation
 * @property {string} name.required - the name of the category (simple format: underscores and no caps or spaces)
 * @property {display_name} display_name.required - display name of category (include capitalization and spacing)
 * @property {description} description - description of the category
 */
class Categories extends Collection {}

module.exports = new Categories(schema);
