'use strict';

const Collection = require('./collection.js');
const schema = {
  id: { type: 'string', required: true },
  category: { type: 'string', required: true },
  name: { type: 'string', required: true },
  display_name: { type: 'string' },
  description: { type: 'string' },
};

/**
 * @typedef Products
 * @property {string} id.required - unique ID generated by uuid upon creation
 * @property {string} category.required - the associated category name (must match an existing category name)
 * @property {string} name.required - the name of the product (simple format:underscores and no caps or spaces)
 * @property {display_name} display_name.required - display name of product (include capitalization and spacing)
 * @property {description} description - description of the product
 */
class Products extends Collection {}

module.exports = new Products(schema);
